version: '3'
services:
  backend:
    build:
      context: ./path/to/backend
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./path/to/frontend
    ports:
      - "3000:80"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
